version: '3.8'

services:
  app:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/around_home
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: around_home_development
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
